# -*- coding: utf-8 -*-
"""03_claim_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uf-G47pQtWftIaoFfJmWL-HjOior4yK0
"""

# =====================================================================
# DATA PREPARATION & FINANCIAL FEATURE SELECTION
# =====================================================================
import pandas as pd
import joblib
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv('model_table.csv')

# Ensure date is sorted for time-based split
df['visit_date'] = pd.to_datetime(df['visit_date'])
df = df.sort_values('visit_date').reset_index(drop=True)

# 1. Feature Selection for Model B (Claim Outcome)
# CRITICAL: We MUST drop 'approved_amount' and 'payment_days'. These are post-submission
# variables. If we include them, the model cheats (Data Leakage).
financial_features = ['age', 'chronic_flag', 'department', 'risk_score',
                      'insurance_provider', 'provider_rejection_rate', 'billed_amount']
target = 'claim_status'

X_claim = df[financial_features]
y_claim = df[target]

# 2. Analyze Class Imbalance (Rubric Requirement)
print("--- CLASS IMBALANCE CHECK ---")
print(y_claim.value_counts(normalize=True) * 100)

# 3. Categorical Encoding
X_claim_encoded = pd.get_dummies(X_claim, drop_first=True)

"""***Class Imbalance & Leakage Strategy:***

For the Claim Outcome model, we engineered predictor features based heavily on financial history (provider_rejection_rate, billed_amount, insurance_provider). It is absolutely critical that approved_amount and payment_days were excluded, as those variables only exist after a claim is processed, representing catastrophic data leakage.

A review of the target variable reveals class imbalance (the vast majority of claims are 'Paid', with 'Rejected' representing a minority). If ignored, the model will simply predict 'Paid' every time to achieve high accuracy. We will mitigate this using algorithm-level penalization (class_weight='balanced') to force the model to pay equal attention to minority class rejections.
"""

# =====================================================================
# TIME-BASED SPLIT & GRADIENT BOOSTING MODEL
# =====================================================================
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.utils.class_weight import compute_sample_weight
from sklearn.metrics import classification_report

# 1. Time-Based Split (80/20)
split_idx = int(len(X_claim_encoded) * 0.80)
X_c_train, X_c_test = X_claim_encoded.iloc[:split_idx], X_claim_encoded.iloc[split_idx:]
y_c_train, y_c_test = y_claim.iloc[:split_idx], y_claim.iloc[split_idx:]

# 2. Baseline Model (Logistic Regression with class balancing)
log_claim = LogisticRegression(max_iter=1000, class_weight='balanced', random_state=42)
log_claim.fit(X_c_train, y_c_train)

print("--- BASELINE MODEL: LOGISTIC REGRESSION ---")
print(classification_report(y_c_test, log_claim.predict(X_c_test)))

# 3. Advanced Model (Gradient Boosting)
# We compute sample weights to feed the Gradient Booster to handle the class imbalance
sample_weights = compute_sample_weight(class_weight='balanced', y=y_c_train)

gb_model = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=5, random_state=42)
gb_model.fit(X_c_train, y_c_train, sample_weight=sample_weights)

print("--- ADVANCED MODEL: GRADIENT BOOSTING ---")
print(classification_report(y_c_test, gb_model.predict(X_c_test)))

# 4. Export Artifact
joblib.dump(gb_model, 'claim_model.joblib')
print("\nSUCCESS: 'claim_model.joblib' saved successfully.")

"""***Analysis of Class Imbalance & Mitigation Strategy (Model B)***


***1. The Imbalance Problem (The Accuracy Paradox)***

In hospital billing data, the target variable claim_status is inherently imbalanced. The vast majority of historical claims are successfully processed and marked as 'Paid' (often 80%+ of the dataset), while 'Rejected' and 'Pending' claims represent the minority classes.

If we train a standard Machine Learning model on this raw data without intervention, it falls victim to the "Accuracy Paradox." The model realizes that simply predicting 'Paid' for every single claim will yield an 80%+ overall accuracy. However, a model that never predicts a rejection is functionally useless to the hospital's finance team, as the entire business goal is to proactively identify those specific rejected claims.

***2. The Chosen Mitigation Strategy: Algorithmic Penalization***

To solve this without artificially altering our dataset (such as using SMOTE to synthesize fake data or undersampling which deletes valid data), we employed Cost-Sensitive Learning via algorithmic penalization.

***Implementation:***  In both our Baseline (Logistic Regression) and Advanced (Gradient Boosting) models, we utilized the class_weight='balanced' parameter and compute_sample_weight functions from Scikit-Learn.

***How it Works:***  This mathematical adjustment calculates the frequency of each class and assigns inverse weights. Because 'Rejected' claims are rare, the algorithm assigns a massive mathematical penalty to the model every time it misclassifies one. Conversely, misclassifying a common 'Paid' claim incurs a very small penalty.

***The Result:***  This forces the Gradient Boosting model to pay disproportionate attention to the financial and operational patterns that lead to rejections, resulting in much higher precision and recall for the minority class without distorting the underlying historical data.
"""